school_city_map = {
    'CINCINNATI CSD':'Cincinnati', 
    'DEER PARK CSD':'Cincinnati',
    'FINNEYTOWN LSD':'Cincinnati',
    'FOREST HILLS LSD':'Cincinnati',
    'INDIAN HILL EVSD':'Indian Hills',
    'LOCKLAND CSD': 'Cincinnati',
    'LOVELAND CSD':'Loveland', 
    'NORTHWEST LSD (HAMILTON CO.)':'Cincinnati',
    'MADEIRA CSD':'Madeira', 
    'MARIEMONT CSD':'Mariemont', 
    'MILFORD CSD':'Milford',
    'MOUNT HEALTHY CSD':'Cincinnati',
    'NORTH COLLEGE HILL CSD':'Cincinnati',
    'NORWOOD CSD':'Norwood', 
    'OAK HILLS LSD':'Cincinnati', 
    'PRINCETON CSD':'Cincinnati',
    'READING CSD':'Reading',
    'SOUTHWEST LSD (HAMILTON CO.)':'Harrison',
    'ST. BERNARD-ELMWOOD PLACE CSD':'Cincinnati',
    'SYCAMORE CSD':'Montgomery', 
    'THREE RIVERS LSD':'Cleves',
    'WINTON WOODS CSD':'Cincinnati',
    'WYOMING CSD':'Wyoming'
}

district_idn_map = {
    'CINCINNATI CSD': '043752',
    'DEER PARK CSD': '043851',
    'FINNEYTOWN LSD': '047332',
    'FOREST HILLS LSD': '047340',
    'INDIAN HILL EVSD': '045435',
    'LOCKLAND CSD': '044230',
    'LOVELAND CSD': '044271',
    'MADEIRA CSD': '044289',
    'MARIEMONT CSD': '044313',
    'MILFORD EVSD': '045500',
    'MOUNT HEALTHY CSD': '044412',
    'NORTH COLLEGE HILL CSD': '044511',
    'NORTHWEST LSD (HAMILTON CO.)': '047365',
    'NORWOOD CSD': '044578',
    'OAK HILLS LSD': '047373',
    'PRINCETON CSD': '044677',
    'READING CSD': '044693',
    'SOUTHWEST LSD (HAMILTON CO.)': '047381',
    'ST. BERNARD-ELMWOOD PLACE CSD': '044719',
    'SYCAMORE CSD': '044867',
    'THREE RIVERS LSD': '047399',
    'WINTON WOODS CSD': '044081',
    'WYOMING CSD': '045146'
}

