# Maps *every* commonly-seen spelling / abbreviation → canonical USPS suffix
street_type_map: dict[str, str] = {
    # ――― A ―――
    "AL": "ALLEY",
    "ALY": "ALLEY",
    "ALLEE": "ALLEY",
    "ALLY": "ALLEY",
    "ALLEY": "ALLEY",
    "ANX": "ANNEX",
    "ANEX": "ANNEX",
    "ANNEX": "ANNEX",
    "ARC": "ARCADE",
    "ARCADE": "ARCADE",
    "AV": "AVENUE",
    "AVE": "AVENUE",
    "AVEN": "AVENUE",
    "AVENU": "AVENUE",
    "AVN": "AVENUE",
    "AVNUE": "AVENUE",
    "AVENUE": "AVENUE",
    # ――― B ―――
    "BYU": "BAYOU",
    "BAYOO": "BAYOU",
    "BAYOU": "BAYOU",
    "BCH": "BEACH",
    "BEACH": "BEACH",
    "BND": "BEND",
    "BEND": "BEND",
    "BLF": "BLUFF",
    "BLUF": "BLUFF",
    "BLUFF": "BLUFF",
    "BLFS": "BLUFFS",
    "BLUFFS": "BLUFFS",
    "BTM": "BOTTOM",
    "BOTTM": "BOTTOM",
    "BOT": "BOTTOM",
    "BOTTOM": "BOTTOM",
    "BLVD": "BOULEVARD",
    "BOUL": "BOULEVARD",
    "BOULV": "BOULEVARD",
    "BOULEVARD": "BOULEVARD",
    "BV":"BOULEVARD",
    "BR": "BRANCH",
    "BRNCH": "BRANCH",
    "BRANCH": "BRANCH",
    "BRG": "BRIDGE",
    "BRDGE": "BRIDGE",
    "BRIDGE": "BRIDGE",
    "BRK": "BROOK",
    "BROOK": "BROOK",
    "BRKS": "BROOKS",
    "BROOKS": "BROOKS",
    "BG": "BURG",
    "BURG": "BURG",
    "BGS": "BURGS",
    "BURGS": "BURGS",
    "BYP": "BYPASS",
    "BYPA": "BYPASS",
    "BYPAS": "BYPASS",
    "BYPS": "BYPASS",
    "BYPASS": "BYPASS",
    # ――― C ―――
    "CP": "CAMP",
    "CMP": "CAMP",
    "CAMP": "CAMP",
    "CYN": "CANYON",
    "CNYN": "CANYON",
    "CANYN": "CANYON",
    "CANYON": "CANYON",
    "CPE": "CAPE",
    "CAPE": "CAPE",
    "CSWY": "CAUSEWAY",
    "CAUSEWAY": "CAUSEWAY",
    "CAUSWA": "CAUSEWAY",
    "CEN": "CENTER",
    "CENT": "CENTER",
    "CENTER": "CENTER",
    "CENTR": "CENTER",
    "CENTRE": "CENTER",
    "CNTER": "CENTER",
    "CNTR": "CENTER",
    "CTRS": "CENTERS",
    "CENTERS": "CENTERS",
    "CR": "CIRCLE",
    "CIR": "CIRCLE",
    "CIRC": "CIRCLE",
    "CIRCL": "CIRCLE",
    "CRCL": "CIRCLE",
    "CRCLE": "CIRCLE",
    "CIRCLE": "CIRCLE",
    "CIRS": "CIRCLES",
    "CIRCLES": "CIRCLES",
    "CLF": "CLIFF",
    "CLIFF": "CLIFF",
    "CLFS": "CLIFFS",
    "CLIFFS": "CLIFFS",
    "CLB": "CLUB",
    "CLOSE": "CL",
    "CLUB": "CLUB",
    "CMN": "COMMON",
    "COMMON": "COMMON",
    "CMNS": "COMMONS",
    "COMMONS": "COMMONS",
    "COR": "CORNER",
    "CORNER": "CORNER",
    "CORS": "CORNERS",
    "CORNERS": "CORNERS",
    "CRSE": "COURSE",
    "COURSE": "COURSE",
    "CT": "COURT",
    "COURT": "COURT",
    "CTS": "COURTS",
    "COURTS": "COURTS",
    "CV": "COVE",
    "COVE": "COVE",
    "CVS": "COVES",
    "COVES": "COVES",
    "CRK": "CREEK",
    "CREEK": "CREEK",
    "CRES": "CRESCENT",
    "CRSENT": "CRESCENT",
    "CRSNT": "CRESCENT",
    "CRESCENT": "CRESCENT",
    "CRST": "CREST",
    "CREST": "CREST",
    "XING": "CROSSING",
    "CRSSNG": "CROSSING",
    "CROSSING": "CROSSING",
    "XRD": "CROSSROAD",
    "CROSSROAD": "CROSSROAD",
    "XRDS": "CROSSROADS",
    "CROSSROADS": "CROSSROADS",
    "CURV": "CURVE",
    "CURVE": "CURVE",
    # ――― D ―――
    "DL": "DALE",
    "DALE": "DALE",
    "DM": "DAM",
    "DAM": "DAM",
    "DV": "DIVIDE",
    "DIV": "DIVIDE",
    "DVD": "DIVIDE",
    "DIVIDE": "DIVIDE",
    "DR": "DRIVE",
    "DRIV": "DRIVE",
    "DRV": "DRIVE",
    "DRIVE": "DRIVE",
    "DRS": "DRIVES",
    "DRIVES": "DRIVES",
    # ――― E ―――
    "EST": "ESTATE",
    "ESTATE": "ESTATE",
    "ESTS": "ESTATES",
    "ESTATES": "ESTATES",
    "EXP": "EXPRESSWAY",
    "EXPY": "EXPRESSWAY",
    "EXPR": "EXPRESSWAY",
    "EXPRESS": "EXPRESSWAY",
    "EXPW": "EXPRESSWAY",
    "EXPRESSWAY": "EXPRESSWAY",
    "EXT": "EXTENSION",
    "EXTN": "EXTENSION",
    "EXTNSN": "EXTENSION",
    "EXTENSION": "EXTENSION",
    "EXTS": "EXTENSIONS",
    "EXTENSIONS": "EXTENSIONS",
    # ――― F ―――
    "FALL": "FALL",
    "FLS": "FALLS",
    "FALLS": "FALLS",
    "FRY": "FERRY",
    "FRRY": "FERRY",
    "FERRY": "FERRY",
    "FLD": "FIELD",
    "FIELD": "FIELD",
    "FLDS": "FIELDS",
    "FIELDS": "FIELDS",
    "FLT": "FLAT",
    "FLAT": "FLAT",
    "FLTS": "FLATS",
    "FLATS": "FLATS",
    "FRD": "FORD",
    "FORD": "FORD",
    "FRDS": "FORDS",
    "FORDS": "FORDS",
    "FRST": "FOREST",
    "FOREST": "FOREST",
    "FORG": "FORGE",
    "FRG": "FORGE",
    "FORGE": "FORGE",
    "FRGS": "FORGES",
    "FORGES": "FORGES",
    "FRK": "FORK",
    "FORK": "FORK",
    "FRKS": "FORKS",
    "FORKS": "FORKS",
    "FT": "FORT",
    "FRT": "FORT",
    "FORT": "FORT",
    "FWY": "FREEWAY",
    "FREEWAY": "FREEWAY",
    "FREEWY": "FREEWAY",
    "FRWAY": "FREEWAY",
    "FRWY": "FREEWAY",
    # ――― G ―――
    "GDN": "GARDEN",
    "GARDN": "GARDEN",
    "GRDEN": "GARDEN",
    "GRDN": "GARDEN",
    "GARDEN": "GARDEN",
    "GDNS": "GARDENS",
    "GRDNS": "GARDENS",
    "GARDENS": "GARDENS",
    "GTWY": "GATEWAY",
    "GATEWY": "GATEWAY",
    "GATWAY": "GATEWAY",
    "GTWAY": "GATEWAY",
    "GATEWAY": "GATEWAY",
    "GLN": "GLEN",
    "GLEN": "GLEN",
    "GLNS": "GLENS",
    "GLENS": "GLENS",
    "GRN": "GREEN",
    "GREEN": "GREEN",
    "GRNS": "GREENS",
    "GREENS": "GREENS",
    "GRV": "GROVE",
    "GROV": "GROVE",
    "GROVE": "GROVE",
    "GRVS": "GROVES",
    "GROVES": "GROVES",
    # ――― H ―――
    "HBR": "HARBOR",
    "HARB": "HARBOR",
    "HARBR": "HARBOR",
    "HRBOR": "HARBOR",
    "HARBOR": "HARBOR",
    "HBRS": "HARBORS",
    "HARBORS": "HARBORS",
    "HVN": "HAVEN",
    "HAVEN": "HAVEN",
    "HTS": "HEIGHTS",
    "HT": "HEIGHTS",
    "HEIGHTS": "HEIGHTS",
    "HWY": "HIGHWAY",
    "HIGHWAY": "HIGHWAY",
    "HIGHWY": "HIGHWAY",
    "HIWAY": "HIGHWAY",
    "HIWY": "HIGHWAY",
    "HWAY": "HIGHWAY",
    "HL": "HILL",
    "HILL": "HILL",
    "HLS": "HILLS",
    "HILLS": "HILLS",
    "HOLW": "HOLLOW",
    "HLLW": "HOLLOW",
    "HOLLOW": "HOLLOW",
    "HOLWS": "HOLLOW",
    "HOLLOWS": "HOLLOW",
    # ――― I ―――
    "INLT": "INLET",
    "INLET": "INLET",
    "IS": "ISLAND",
    "ISLND": "ISLAND",
    "ISLAND": "ISLAND",
    "ISS": "ISLANDS",
    "ISLNDS": "ISLANDS",
    "ISLANDS": "ISLANDS",
    "ISLE": "ISLE",
    "ISLES": "ISLES",
    # ――― J ―――
    "JCT": "JUNCTION",
    "JCTION": "JUNCTION",
    "JCTN": "JUNCTION",
    "JUNCTN": "JUNCTION",
    "JUNCTON": "JUNCTION",
    "JUNCTION": "JUNCTION",
    "JCTNS": "JUNCTIONS",
    "JCTS": "JUNCTIONS",
    "JUNCTIONS": "JUNCTIONS",
    # ――― K ―――
    "KY": "KEY",
    "KEY": "KEY",
    "KYS": "KEYS",
    "KEYS": "KEYS",
    "KNL": "KNOLL",
    "KNOL": "KNOLL",
    "KNOLL": "KNOLL",
    "KNLS": "KNOLLS",
    "KNOLLS": "KNOLLS",
    # ――― L ―――
    "LK": "LAKE",
    "LAKE": "LAKE",
    "LKS": "LAKES",
    "LAKES": "LAKES",
    "LAND": "LAND",
    "LNDG": "LANDING",
    "LNDNG": "LANDING",
    "LANDING": "LANDING",
    "LN": "LANE",
    "LANE": "LANE",
    "LGT": "LIGHT",
    "LIGHT": "LIGHT",
    "LGTS": "LIGHTS",
    "LIGHTS": "LIGHTS",
    "LF": "LOAF",
    "LOAF": "LOAF",
    "LCK": "LOCK",
    "LOCK": "LOCK",
    "LCKS": "LOCKS",
    "LOCKS": "LOCKS",
    "LDG": "LODGE",
    "LDGE": "LODGE",
    "LODG": "LODGE",
    "LODGE": "LODGE",
    "LOOP": "LOOP",
    "LOOPS": "LOOP",
    # ――― M ―――
    "MALL": "MALL",
    "MNR": "MANOR",
    "MANOR": "MANOR",
    "MNRS": "MANORS",
    "MANORS": "MANORS",
    "MDW": "MEADOW",
    "MEADOW": "MEADOW",
    "MDWS": "MEADOWS",
    "MEDOWS": "MEADOWS",
    "MEADOWS": "MEADOWS",
    "MEWS": "MEWS",
    "ML": "MILL",
    "MILL": "MILL",
    "MLS": "MILLS",
    "MILLS": "MILLS",
    "MSN": "MISSION",
    "MISSN": "MISSION",
    "MSSN": "MISSION",
    "MISSION": "MISSION",
    "MTWY": "MOTORWAY",
    "MOTORWAY": "MOTORWAY",
    "MT": "MOUNT",
    "MNT": "MOUNT",
    "MOUNT": "MOUNT",
    "MTN": "MOUNTAIN",
    "MNTAIN": "MOUNTAIN",
    "MNTN": "MOUNTAIN",
    "MOUNTIN": "MOUNTAIN",
    "MTIN": "MOUNTAIN",
    "MOUNTAIN": "MOUNTAIN",
    "MTNS": "MOUNTAINS",
    "MNTNS": "MOUNTAINS",
    "MOUNTAINS": "MOUNTAINS",
    # ――― N ―――
    "NCK": "NECK",
    "NECK": "NECK",
    # ――― O ―――
    "ORCH": "ORCHARD",
    "ORCHRD": "ORCHARD",
    "ORCHARD": "ORCHARD",
    "OVAL": "OVAL",
    "OVL": "OVAL",
    "OPAS": "OVERPASS",
    "OVERPASS": "OVERPASS",
    # ――― P ―――
    "PARK": "PARK",
    "PRK": "PARK",
    "PARKS": "PARKS",
    "PKWY": "PARKWAY",
    "PARKWAY": "PARKWAY",
    "PARKWY": "PARKWAY",
    "PKWAY": "PARKWAY",
    "PKY": "PARKWAY",
    "PW": "PARKWAY",
    "PKWYS": "PARKWAYS",
    "PARKWAYS": "PARKWAYS",
    "PASS": "PASS",
    "PSGE": "PASSAGE",
    "PASSAGE": "PASSAGE",
    "PATH": "PATH",
    "PATHS": "PATHS",
    "PIKE": "PIKE",
    "PIKES": "PIKES",
    "PNE": "PINE",
    "PINE": "PINE",
    "PNES": "PINES",
    "PINES": "PINES",
    "PL": "PLACE",
    "PLACE": "PLACE",
    "PLN": "PLAIN",
    "PLAIN": "PLAIN",
    "PLNS": "PLAINS",
    "PLAINS": "PLAINS",
    "PLZ": "PLAZA",
    "PLAZA": "PLAZA",
    "PLZA": "PLAZA",
    "PT": "POINT",
    "POINT": "POINT",
    "PTS": "POINTS",
    "POINTS": "POINTS",
    "PRT": "PORT",
    "PORT": "PORT",
    "PRTS": "PORTS",
    "PORTS": "PORTS",
    "PR": "PRAIRIE",
    "PRAIRIE": "PRAIRIE",
    "PRR": "PRAIRIE",
    # ――― R ―――
    "RAD": "RADIAL",
    "RADL": "RADIAL",
    "RADIEL": "RADIAL",
    "RADIAL": "RADIAL",
    "RAMP": "RAMP",
    "RNCH": "RANCH",
    "RANCH": "RANCH",
    "RNCHS": "RANCHES",
    "RANCHES": "RANCHES",
    "RPD": "RAPID",
    "RAPID": "RAPID",
    "RPDS": "RAPIDS",
    "RAPIDS": "RAPIDS",
    "RST": "REST",
    "REST": "REST",
    "RDG": "RIDGE",
    "RDGE": "RIDGE",
    "RIDGE": "RIDGE",
    "RDGS": "RIDGES",
    "RIDGES": "RIDGES",
    "RIV": "RIVER",
    "RIVR": "RIVER",
    "RVR": "RIVER",
    "RIVER": "RIVER",
    "RD": "ROAD",
    "ROAD": "ROAD",
    "RDS": "ROADS",
    "ROADS": "ROADS",
    "RTE": "ROUTE",
    "ROUTE": "ROUTE",
    "ROW": "ROW",
    "RUE": "RUE",
    "RUN": "RUN",
    # ――― S ―――
    "SHL": "SHOAL",
    "SHOAL": "SHOAL",
    "SHLS": "SHOALS",
    "SHOALS": "SHOALS",
    "SHR": "SHORE",
    "SHOAR": "SHORE",
    "SHORE": "SHORE",
    "SHRS": "SHORES",
    "SHOARS": "SHORES",
    "SHORES": "SHORES",
    "SKWY": "SKYWAY",
    "SKYWAY": "SKYWAY",
    "SPG": "SPRING",
    "SPNG": "SPRING",
    "SPRNG": "SPRING",
    "SPRING": "SPRING",
    "SPGS": "SPRINGS",
    "SPNGS": "SPRINGS",
    "SPRNGS": "SPRINGS",
    "SPRINGS": "SPRINGS",
    "SPUR": "SPUR",
    "SPURS": "SPURS",
    "SQ": "SQUARE",
    "SQR": "SQUARE",
    "SQRE": "SQUARE",
    "SQU": "SQUARE",
    "SQUARE": "SQUARE",
    "SQRS": "SQUARES",
    "SQS": "SQUARES",
    "SQUARES": "SQUARES",
    "STA": "STATION",
    "STATN": "STATION",
    "STN": "STATION",
    "STATION": "STATION",
    "STRA": "STRAVENUE",
    "STRAV": "STRAVENUE",
    "STRAVEN": "STRAVENUE",
    "STRAVN": "STRAVENUE",
    "STRVN": "STRAVENUE",
    "STRVNUE": "STRAVENUE",
    "STRAVENUE": "STRAVENUE",
    "STRM": "STREAM",
    "STREME": "STREAM",
    "STREAM": "STREAM",
    "ST": "STREET",
    "STR": "STREET",
    "STRT": "STREET",
    "STREET": "STREET",
    "STS": "STREETS",
    "STREETS": "STREETS",
    "SMT": "SUMMIT",
    "SUMIT": "SUMMIT",
    "SUMITT": "SUMMIT",
    "SUMMIT": "SUMMIT",
    # ――― T ―――
    "TE": "TERRACE",
    "TER": "TERRACE",
    "TERR": "TERRACE",
    "TERRACE": "TERRACE",
    "TRWY": "THROUGHWAY",
    "THROUGHWAY": "THROUGHWAY",
    "TRCE": "TRACE",
    "TRACE": "TRACE",
    "TRAK": "TRACK",
    "TRACK": "TRACK",
    "TRKS": "TRACKS",
    "TRK": "TRACKS",
    "TRACKS": "TRACKS",
    "TRFY": "TRAFFICWAY",
    "TRAFFICWAY": "TRAFFICWAY",
    "TL": "TRAIL",
    "TRL": "TRAIL",
    "TRAIL": "TRAIL",
    "TRLS": "TRAILS",
    "TRAILS": "TRAILS",
    "TRLR": "TRAILER",
    "TRLRS": "TRAILER",
    "TRAILER": "TRAILER",
    "TURN": "TURN",
    "TUNL": "TUNNEL",
    "TUNLS": "TUNNEL",
    "TUNEL": "TUNNEL",
    "TUNNL": "TUNNEL",
    "TUNNEL": "TUNNEL",
    "TPKE": "TURNPIKE",
    "TRNPK": "TURNPIKE",
    "TURNPK": "TURNPIKE",
    "TURNPIKE": "TURNPIKE",
    "UPAS": "UNDERPASS",
    "UNDERPASS": "UNDERPASS",
    # ――― U ―――
    "UN": "UNION",
    "UNION": "UNION",
    "UNS": "UNIONS",
    "UNIONS": "UNIONS",
    # ――― V ―――
    "VLY": "VALLEY",
    "VALLY": "VALLEY",
    "VLLY": "VALLEY",
    "VALLEY": "VALLEY",
    "VLYS": "VALLEYS",
    "VALLEYS": "VALLEYS",
    "VIA": "VIADUCT",
    "VDCT": "VIADUCT",
    "VIADCT": "VIADUCT",
    "VIADUCT": "VIADUCT",
    "VW": "VIEW",
    "VIEW": "VIEW",
    "VWS": "VIEWS",
    "VIEWS": "VIEWS",
    "VLG": "VILLAGE",
    "VILL": "VILLAGE",
    "VILLAG": "VILLAGE",
    "VILLG": "VILLAGE",
    "VILLIAGE": "VILLAGE",
    "VILLAGE": "VILLAGE",
    "VLGS": "VILLAGES",
    "VILLAGES": "VILLAGES",
    "VL": "VILLE",
    "VILLE": "VILLE",
    "VIS": "VISTA",
    "VST": "VISTA",
    "VSTA": "VISTA",
    "VIST": "VISTA",
    "VISTA": "VISTA",
    # ――― W ―――
    "WALK": "WALK",
    "WALKS": "WALK",
    "WALL": "WALL",
    "WY": "WAY",
    "WAY": "WAY",
    "WAYS": "WAYS",
    "WL": "WELL",
    "WELL": "WELL",
    "WLS": "WELLS",
    "WELLS": "WELLS",
}

# Canonical street-suffix  ➜  USPS standard suffix abbreviation
canonical_to_abbrev: dict[str, str] = {
    # ――― A ―――
    "ALLEY": "ALY",
    "ANNEX": "ANX",
    "ARCADE": "ARC",
    "AVENUE": "AVE",
    # ――― B ―――
    "BAYOU": "BYU",
    "BEACH": "BCH",
    "BEND": "BND",
    "BLUFF": "BLF",
    "BLUFFS": "BLFS",
    "BOTTOM": "BTM",
    "BOULEVARD": "BLVD",
    "BRANCH": "BR",
    "BRIDGE": "BRG",
    "BROOK": "BRK",
    "BROOKS": "BRKS",
    "BURG": "BG",
    "BURGS": "BGS",
    "BYPASS": "BYP",
    # ――― C ―――
    "CAMP": "CP",
    "CANYON": "CYN",
    "CAPE": "CPE",
    "CAUSEWAY": "CSWY",
    "CENTER": "CTR",
    "CENTERS": "CTRS",
    "CIRCLE": "CIR",
    "CIRCLES": "CIRS",
    "CLIFF": "CLF",
    "CLIFFS": "CLFS",
    "CLUB": "CLB",
    "COMMON": "CMN",
    "COMMONS": "CMNS",
    "CORNER": "COR",
    "CORNERS": "CORS",
    "COURSE": "CRSE",
    "COURT": "CT",
    "COURTS": "CTS",
    "COVE": "CV",
    "COVES": "CVS",
    "CREEK": "CRK",
    "CRESCENT": "CRES",
    "CREST": "CRST",
    "CROSSING": "XING",
    "CROSSROAD": "XRD",
    "CROSSROADS": "XRDS",
    "CURVE": "CURV",
    # ――― D ―――
    "DALE": "DL",
    "DAM": "DM",
    "DIVIDE": "DV",
    "DRIVE": "DR",
    "DRIVES": "DRS",
    # ――― E ―――
    "ESTATE": "EST",
    "ESTATES": "ESTS",
    "EXPRESSWAY": "EXPY",
    "EXTENSION": "EXT",
    "EXTENSIONS": "EXTS",
    # ――― F ―――
    "FALL": "FALL",
    "FALLS": "FLS",
    "FERRY": "FRY",
    "FIELD": "FLD",
    "FIELDS": "FLDS",
    "FLAT": "FLT",
    "FLATS": "FLTS",
    "FORD": "FRD",
    "FORDS": "FRDS",
    "FOREST": "FRST",
    "FORGE": "FRG",
    "FORGES": "FRGS",
    "FORK": "FRK",
    "FORKS": "FRKS",
    "FORT": "FT",
    "FREEWAY": "FWY",
    # ――― G ―――
    "GARDEN": "GDN",
    "GARDENS": "GDNS",
    "GATEWAY": "GTWY",
    "GLEN": "GLN",
    "GLENS": "GLNS",
    "GREEN": "GRN",
    "GREENS": "GRNS",
    "GROVE": "GRV",
    "GROVES": "GRVS",
    # ――― H ―――
    "HARBOR": "HBR",
    "HARBORS": "HBRS",
    "HAVEN": "HVN",
    "HEIGHTS": "HTS",
    "HIGHWAY": "HWY",
    "HILL": "HL",
    "HILLS": "HLS",
    "HOLLOW": "HOLW",
    # ――― I ―――
    "INLET": "INLT",
    "ISLAND": "IS",
    "ISLANDS": "ISS",
    "ISLE": "ISLE",
    # ――― J ―――
    "JUNCTION": "JCT",
    "JUNCTIONS": "JCTS",
    # ――― K ―――
    "KEY": "KY",
    "KEYS": "KYS",
    "KNOLL": "KNL",
    "KNOLLS": "KNLS",
    # ――― L ―――
    "LAKE": "LK",
    "LAKES": "LKS",
    "LAND": "LAND",
    "LANDING": "LNDG",
    "LANE": "LN",
    "LIGHT": "LGT",
    "LIGHTS": "LGTS",
    "LOAF": "LF",
    "LOCK": "LCK",
    "LOCKS": "LCKS",
    "LODGE": "LDG",
    "LOOP": "LOOP",
    # ――― M ―――
    "MALL": "MALL",
    "MANOR": "MNR",
    "MANORS": "MNRS",
    "MEADOW": "MDW",
    "MEADOWS": "MDWS",
    "MEWS": "MEWS",
    "MILL": "ML",
    "MILLS": "MLS",
    "MISSION": "MSN",
    "MOTORWAY": "MTWY",
    "MOUNT": "MT",
    "MOUNTAIN": "MTN",
    "MOUNTAINS": "MTNS",
    # ――― N ―――
    "NECK": "NCK",
    # ――― O ―――
    "ORCHARD": "ORCH",
    "OVAL": "OVAL",
    "OVERPASS": "OPAS",
    # ――― P ―――
    "PARK": "PARK",
    "PARKS": "PARKS",
    "PARKWAY": "PKWY",
    "PARKWAYS": "PKWY",
    "PASS": "PASS",
    "PASSAGE": "PSGE",
    "PATH": "PATH",
    "PK":"PIKE",
    "PIKE": "PIKE",
    "PINE": "PNE",
    "PINES": "PNES",
    "PLACE": "PL",
    "PLAIN": "PLN",
    "PLAINS": "PLNS",
    "PLAZA": "PLZ",
    "POINT": "PT",
    "POINTS": "PTS",
    "PORT": "PRT",
    "PORTS": "PRTS",
    "PRAIRIE": "PR",
    # ――― R ―――
    "RADIAL": "RADL",
    "RAMP": "RAMP",
    "RANCH": "RNCH",
    "RANCHES": "RNCHS",
    "RAPID": "RPD",
    "RAPIDS": "RPDS",
    "REST": "RST",
    "RIDGE": "RDG",
    "RIDGES": "RDGS",
    "RIVER": "RIV",
    "ROAD": "RD",
    "ROADS": "RDS",
    "ROUTE": "RTE",
    "ROW": "ROW",
    "RUE": "RUE",
    "RUN": "RUN",
    # ――― S ―――
    "SHOAL": "SHL",
    "SHOALS": "SHLS",
    "SHORE": "SHR",
    "SHORES": "SHRS",
    "SKYWAY": "SKWY",
    "SPRING": "SPG",
    "SPRINGS": "SPGS",
    "SPUR": "SPUR",
    "SQUARE": "SQ",
    "SQUARES": "SQRS",
    "STATION": "STA",
    "STRAVENUE": "STRA",
    "STREAM": "STRM",
    "STREET": "ST",
    "STREETS": "STS",
    "SUMMIT": "SMT",
    # ――― T ―――
    "TERRACE": "TER",
    "THROUGHWAY": "TRWY",
    "TRACE": "TRCE",
    "TRACK": "TRAK",
    "TRACKS": "TRKS",
    "TRAFFICWAY": "TRFY",
    "TRAIL": "TRL",
    "TRAILS": "TRLS",
    "TRAILER": "TRLR",
    "TUNNEL": "TUNL",
    "TURNPIKE": "TPKE",
    # ――― U ―――
    "UNDERPASS": "UPAS",
    "UNION": "UN",
    "UNIONS": "UNS",
    # ――― V ―――
    "VALLEY": "VLY",
    "VALLEYS": "VLYS",
    "VIADUCT": "VIA",
    "VIEW": "VW",
    "VIEWS": "VWS",
    "VILLAGE": "VLG",
    "VILLAGES": "VLGS",
    "VILLE": "VL",
    "VISTA": "VIS",
    # ――― W ―――
    "WALK": "WALK",
    "WALL": "WALL",
    "WAY": "WAY",
    "WAYS": "WAYS",
    "WELL": "WL",
    "WELLS": "WLS",
}

# Some canonical forms don’t appear in canonical_to_abbrev; map them to
# the closest USPS style manually.
_suffix_abbrev_fallbacks: dict[str, str] = {
    "ISLES": "ISLE",
    "PATHS": "PATH",
    "PIKES": "PIKE",
    "SPURS": "SPUR",
}

# Fully normalized: messy input token → USPS suffix abbreviation
street_suffix_normalization_map: dict[str, str] = {}
for variant, canonical in street_type_map.items():
    abbr = (
        canonical_to_abbrev.get(canonical)
        or _suffix_abbrev_fallbacks.get(canonical)
        or canonical
    )
    street_suffix_normalization_map[variant] = abbr

direction_map = {
    "N": "NORTH",
    "S": "SOUTH",
    "E": "EAST",
    "W": "WEST",
    "NW": "NORTHWEST",
    "SW": "SOUTHWEST",
    "NE": "NORTHEAST",
    "SE": "SOUTHEAST",
}

street_prefix_map = {
    # Saint / Sainte / Saints
    "ST": "SAINT",
    "ST.": "SAINT",
    "STE": "SAINTE",
    "STE.": "SAINTE",
    "STS": "SAINTS",
    "STS.": "SAINTS",
    # Spanish-language saints
    "SAN": "SAN",
    "SANTA": "SANTA",
    "SANTO": "SANTO",
    "SANTOS": "SANTOS",
    # Mount / Mountain
    "MT": "MOUNT",
    "MT.": "MOUNT",
    "MTN": "MOUNTAIN",
    "MTN.": "MOUNTAIN",
    # Fort
    "FT": "FORT",
    "FT.": "FORT",
    # Point
    "PT": "POINT",
    "PT.": "POINT",
    # Lake
    "LK": "LAKE",
    "LK.": "LAKE",
    # Peak / Park  (choose meaning at runtime if context matters)
    "PK": "PEAK",
    "PK.": "PEAK",
    # Port
    "PORT": "PORT",
    "PRT": "PORT",
}

direction_full_to_abbrev_map = {
    "SOUTH": "S",
    "NORTH": "N",
    "EAST": "E",
    "WEST": "W",
    "NORTHEAST": "NE",
    "SOUTHEAST": "SE",
    "NORTHWEST": "NW",
    "SOUTHWEST": "SW",
}


direction_abbrev_to_full = {
    "N": "NORTH",
    "S": "SOUTH",
    "E": "EAST",
    "W": "WEST",
    "NW": "NORTHWEST",
    "SW": "SOUTHWEST",
    "NE": "NORTHEAST",
    "SE": "SOUTHEAST",
}

direction_full_to_abbrev: dict[str, str] = {
    full: abbr for abbr, full in direction_abbrev_to_full.items()
}

# Normalize any direction-ish token to USPS abbreviation
direction_normalization_map: dict[str, str] = {
    # already-abbrev inputs
    **{abbr: abbr for abbr in direction_abbrev_to_full},
    # full-word inputs
    **direction_full_to_abbrev,
}
